version: '3.9'
services:
  web-client:
    build:
      context: ./web-client
      dockerfile: ../setup/Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - VOTE_API_BASE_URL=http://vote-api:8080
    ports:
      - "3000:3000"
    depends_on:
      - vote-api
    networks:
      - app-network
  vote-api:
    build:
      context: ./vote-api
      dockerfile: ../setup/API/Dockerfile
      target: production
    environment:
      - PG_URL=postgresql://neondb_owner:vz7XbCVfHe8A@ep-little-dust-a5g3mx3a.us-east-2.aws.neon.tech/neondb?sslmode=require
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
  docs:
    build:
      context: ./docs
      dockerfile: ../setup/Doc/Dockerfile
      target: production
    ports:
      - "4000:4000"
    networks:
      - app-network
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./setup/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-client
      - docs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: