name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push web-client Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./web-client
        push: true
        tags: |
          anthony/web-client:latest
          anthony/web-client:${{ github.sha }}

    - name: Build and push docs Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docs
        push: true
        tags: |
          anthony/docs:latest
          anthony/docs:${{ github.sha }}

    - name: Build and push vote-api Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./vote-api
        push: true
        tags: |
          anthony/vote-api:latest
          anthony/vote-api:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Assuming you have a Docker Compose file in the root directory
        docker-compose pull
        docker-compose up -d