name: CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch for merging into main"
        required: true
        default: "develop"
jobs:
  lint-and-test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Execute Linter
        run: |
          echo "Running linting... (currently just a placeholder)"
      - name: Execute Tests
        run: |
          echo "Executing tests... (currently just a placeholder)"
  merge-to-main-job:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Merge Changes to Main
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge ${{ github.event.inputs.target_branch }}
          git push origin main
